name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo " check out "
      - name: build
        run: echo "build artifact "
